layout_spectrum: 0.7310997
color:
  saturation: 1
  brandStrength: 0.9714634
  lightness: 0.680851
  rhythmicContrast: 0.7127659
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
typography_spectrum: 0.5404951
name: Yorkshire Wildlife Park
