name: YWP
favicon: null
layout_spectrum: 0.6124
typography_spectrum: 0.5404951
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#749055'
    - '#746c69'
    - '#412e1d'
    - '#bdaba1'
    - '#aa793f'
  brandStrength: 0.1875
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.7127659
purpose: []
